const WORKING_BOUND_START = 480;
const WORKING_BOUND_END = 1079;
const MEETING_DURATION = 59;
const WEEK_DAYS_COUNT = 5;

module.exports = {
  WORKING_BOUND_END,
  WORKING_BOUND_START,
  WEEK_DAYS_COUNT,
  MEETING_DURATION,
};
